language: python

python:
  - "3.6"

before_install:
  # work around https://github.com/travis-ci/travis-ci/issues/8363
  - pyenv global system 3.5

install:
  - pip install tox

script:
  - tox

sudo: False
